name: PR

on:
  push:
  schedule:
    - cron: '20 9 * * *'

jobs:
  abc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y/%m/%d')"

      # - name: pull-request-action
      #   uses: vsoch/pull-request-action@1.0.6
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PULL_REQUEST_BRANCH: master
      #     PULL_REQUEST_FROM_BRANCH: develop
      #     PULL_REQUEST_ASSIGNEES: jhanjhenyi
      #     PULL_REQUEST_TITLE: sync develop ${{ steps.date.outputs.date }}

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "develop"
          destination_branch: "master"
          pr_title: sync develop ${{ steps.date.outputs.date }}
          pr_assignee: jhanjhenyi
          pr_label: "Type: Maintenance"
          github_token: ${{ secrets.GITHUB_TOKEN }}
