name: PR

on:
  schedule:
    - cron: '15 8 * * *'

jobs:
  abc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y/%m/%d')"

      # - name: pull-request-action
      #   uses: vsoch/pull-request-action@1.0.6
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PULL_REQUEST_BRANCH: master
      #     PULL_REQUEST_FROM_BRANCH: develop
      #     PULL_REQUEST_ASSIGNEES: jhanjhenyi
      #     PULL_REQUEST_TITLE: sync develop ${{ steps.date.outputs.date }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: develop
          base: master
          title: sync develop ${{ steps.date.outputs.date }}
