name: PR

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  abc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # Make changes to pull request here

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     branch: develop
      #     assignees: JhenYi Jhan

      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_FROM_BRANCH: develop
