name: PR

on:
  schedule:
    - cron: '* * * * *'

jobs:
  abc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: master
