name: PR

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  abc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2


      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_FROM_BRANCH: develop
          PULL_REQUEST_ASSIGNEES: JhenYi Jhan
          PULL_REQUEST_TITLE: sync develop ${{ steps.date.outputs.date }}
