name: Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed


jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: My first step
        if: github.event.pull_request.merged == true && github.head_ref == 'develop' && github.base_ref == 'master'
        env:
          GITHUB_CONTEXT: ${{ github.event.pull_request.body }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
