name: Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:


jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: My first step
        if: github.event.pull_request.merged == true && github.head_ref == 'develop' && github.base_ref == 'master'
        env:
          GITHUB_CONTEXT: ${{ github.event.pull_request.body }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
