name: Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed


jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: My first step
        # if: github.event.pull_request.merged == true
        run: echo This event is a pull request that had an assignee removed.

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
